### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by bguzmanrio** [slok/grafterm#45]
Hi! This looks amazing, but I am having some troubles while trying on windows. I am not sure if I have to install it somehow, but I guess I don't have to. Therefore, I try to run it on the command console, with this result:

![graftermIssue](https://user-images.githubusercontent.com/9370052/57986655-f153ab00-7a77-11e9-8f2c-6a1b8d8892ef.JPG)

I hope it helps!

**Comment by slok** [comment]
Hey @bguzmanrio!

I managed to spin up a VM with Windows 10 and test the binary. I didn't see the problem you point on the issue:

![](https://i.imgur.com/UTkP21I.png)

I seem to work, I guess we would have a similar experience to the *nix OSs if I set the correct fonts a use a good terminal.

Closing the issue, thanks!
