### ISSUE TITLE
Arm release missing

### ISSUE THREAD

**Issue by gabrielsson** [slok/grafterm#51]
Using GOARM=7 GOARCH=arm for a fourth release in build.sh so it can be used on raspberry pi would be very handy. This is such a neat project to be able to run on my raspberry pi cluster, showing on the little 3.5" screen.

**Comment by slok** [comment]
Hey @gabrielsson!

You are right, that would be very helpful, I'll make a binary and try myself on a few days to check it works correctly, add to the release process and get a new version of the Grafterm (with Graphite support) that I have been postponing.

Thank you!

**Comment by slok** [comment]
Hi @gabrielsson I just released [v0.2.0](https://github.com/slok/grafterm/releases/tag/v0.2.0) with the ARM builds!

**Comment by gabrielsson** [comment]
Great, will use this right after vacation!
